// Breed list used by the autocomplete component
// Covers the most common dog breeds

export const dogBreeds: string[] = [
  // A
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Bulldog',
  'American Cocker Spaniel',
  'American Staffordshire Terrier',
  'Anatolian Shepherd',
  'Australian Cattle Dog',
  'Australian Shepherd',
  'Australian Terrier',
  // B
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Bedlington Terrier',
  'Belgian Malinois',
  'Belgian Shepherd',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Bloodhound',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Boxer',
  'Briard',
  'Brittany Spaniel',
  'Brussels Griffon',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  // C
  'Cairn Terrier',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Cavalier King Charles Spaniel',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chinese Crested',
  'Chinese Shar-Pei',
  'Chow Chow',
  'Clumber Spaniel',
  'Cocker Spaniel',
  'Collie',
  'Coton de Tulear',
  'Curly-Coated Retriever',
  // D
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'Dogue de Bordeaux',
  'Dutch Shepherd',
  // E
  'English Pointer',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Spaniel',
  // F
  'Field Spaniel',
  'Finnish Lapphund',
  'Flat-Coated Retriever',
  'Fox Terrier',
  'French Bulldog',
  // G
  'German Pinscher',
  'German Shepherd',
  'German Shorthaired Pointer',
  'German Spitz',
  'German Wirehaired Pointer',
  'Golden Retriever',
  'Gordon Setter',
  'Great Dane',
  'Great Pyrenees',
  'Greyhound',
  // H
  'Havanese',
  // I
  'Ibizan Hound',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  // J
  'Jack Russell Terrier',
  'Japanese Chin',
  'Japanese Spitz',
  // K
  'Keeshond',
  'Kerry Blue Terrier',
  'King Charles Spaniel',
  'Komondor',
  // L
  'Labradoodle',
  'Labrador Retriever',
  'Lancashire Heeler',
  'Leonberger',
  'Lhasa Apso',
  'Lurcher',
  // M
  'Maltese',
  'Manchester Terrier',
  'Mastiff',
  'Miniature Bull Terrier',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  // N
  'Neapolitan Mastiff',
  'Newfoundland',
  'Norfolk Terrier',
  'Norwegian Elkhound',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  // O
  'Old English Sheepdog',
  'Otterhound',
  // P
  'Papillon',
  'Parson Russell Terrier',
  'Patterdale Terrier',
  'Pembroke Welsh Corgi',
  'Pharaoh Hound',
  'Pointer',
  'Pomeranian',
  'Poodle',
  'Portuguese Water Dog',
  'Pug',
  'Puli',
  // R
  'Rhodesian Ridgeback',
  'Rottweiler',
  // S
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Schipperke',
  'Scottish Terrier',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Siberian Husky',
  'Silky Terrier',
  'Skye Terrier',
  'Soft Coated Wheaten Terrier',
  'Spanish Water Dog',
  'Spinone Italiano',
  'Springer Spaniel',
  'Staffordshire Bull Terrier',
  'Swedish Vallhund',
  // T
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  // V
  'Vizsla',
  // W
  'Weimaraner',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Wire Fox Terrier',
  'Wirehaired Vizsla',
  // Y
  'Yorkshire Terrier',

  // Mixed 
  'Mixed Breed / Other',
];
