// This file includes all the functions required to interact with Firestore

// Import necessary modules

import { db } from '@/config/firebase';
import { Like, Pet, User } from '@/types/database';
import {
    addDoc,
    collection, doc, getDoc, getDocs,
    limit,
    orderBy,
    query,
    setDoc,
    Timestamp,
    where
} from 'firebase/firestore';


// Firestore collections
const COLLECTIONS = { 
    USERS: 'users', 
    PETS: 'pets', 
    LIKES: 'likes',
    MATCHES: 'matches',
    CHATS: 'chats',
    EVENTS: 'events'
}; 

// create a new user document in Firestore when a user signs up
export const createUserDocument = async ( 
    userId: string,
    email: string,
    name: string,
    age: number,
    location: string,
    bio?: string
): Promise<void> => { 
    try {
        // create a reference to save the info
        const userRef = doc(db, COLLECTIONS.USERS, userId);

        // Build the user data object
        const userData: User = {
            id: userId,
            email,
            name, 
            age, 
            location, 
            geopoint: {
                latitude: 0, // placeholders for now
                longitude: 0
            }, 
            //default profile picture 
            profilePicture: 'https://www.nicepng.com/png/full/115-1150821_default-avatar-comments-sign-in-icon-png.png${userId}',
            bio: bio || 'Pet lover! :) ', // default bio so it isn't empy if user doesn't provide a bio
            verified: false,
            isActive: true,
            createdAt: new Date()
        };
        
        // Save to firestore!
        await setDoc(userRef, {
            ... userData, 
            createdAt: Timestamp.fromDate(userData.createdAt)
        });
        
        // show the user has been created in console (for debugging)
        console.log('User doc created: ', userId);

    } catch (error) { 
        console.error('Error creating a user doc', error);
        throw error;
    }
};

// Get user doc by ID
export const getUserById = async (userId: string): Promise<User | null > => {
    
    try {
        // Create a reference to the user doc
        const userRef = doc(db, COLLECTIONS.USERS, userId);
        // Gets the doc from Firestore 
        const userSnap = await getDoc(userRef);

        if (userSnap.exists()) {
            // if document exists, gets the data
            const data = userSnap.data();

            return {
                ... data,
                createdAt: data.createdAt.toDate()
            } as User;
        }
        // if it doesn't exist, returns null
        return null;

    } catch (error) {
            console.error('Error getting user: ', error);
            return null;
    }
};

// Get all the users (for testing!)

export const getAllUsers = async (): Promise <User[]> => {
    try {
        // Get the reference to the whole collection 
        const usersRef = collection(db, COLLECTIONS.USERS); 
        const snapshot = await getDocs(usersRef);

        // Get firestore data and transform it to user data
        return snapshot.docs.map(doc => ({
            ... doc.data(), // Gets all the fields from the document
            createdAt: doc.data().createdAt.toDate()
        } as User));

    } catch (error) {
        console.error('Error getting the users: ', error);
        return [];
    }
};

// Create Pet when a user adds a new pet to their profile

export const createPet = async (
     petData: Omit<Pet, 'id'> //shows interface without the id field as it's generated by firestore
): Promise<string> => {
    try {
        // Get reference to pets collection
        const petsRef = collection(db, COLLECTIONS.PETS);

        // Add doc with an auto-generated ID 
        const docRef = await addDoc(petsRef, {
            ... petData, 
            createdAt: Timestamp.fromDate(petData.createdAt),
            updatedAt: Timestamp.fromDate(petData.updatedAt),
        });

        console.log('Pet created: ', docRef.id);
        return docRef.id;

    } catch (error) {
        console.error('Error creating the pet: ', error)
        throw error;
    }
};

// Get the active pets (for the explore screen)

export const getActivePets = async (): Promise<Pet[]> => {

    try {
        const petsRef = collection(db, COLLECTIONS.PETS);

        // Build the query
        const q = query(
            petsRef, 
            where('active', '==', true),
            orderBy('createdAt', 'desc')
        );

        // Executes the query 
        const snapshot = await getDocs(q);

        // Turns the docs from firestore to pet objects
        return snapshot.docs.map(doc => {
            const data = doc.data();

            return { 
                id: doc.id,
                ...data,

                createdAt: data.createdAt.toDate(),
                updatedAt: data.updatedAt.toDate(),
            
                verification: {
                    ...data.verification, 
                    verifiedAt: data.verification.verifiedAt?.toDate()
                }
            } as Pet;
        });
    } catch (error) {
        console.error('Error getting pets: ', error)
        return[];
    }
};

// Get Pets by owner ID 
export const getPetsByOwnerId = async (ownerId: string): Promise<Pet[]> => {

    try {
        const petsRef = collection(db, COLLECTIONS.PETS);
        // Get the collection reference
        const q = query(
            petsRef, 
            where('ownerId', '==', ownerId)
        );

        // Execute query 
        const snapshot = await getDocs(q);

        // Turns docs to pet objects
        return snapshot.docs.map(doc => {
            const data = doc.data();
            return {
                id: doc.id,
                ...data,
                createdAt: data.createdAt.toDate(),
                updatedAt: data.updatedAt.toDate(),
                verification: {
                    ...data.verification,
                    verifiedAt: data.verification.verifiedAt?.toDate()
                }
            } as Pet; 
        });
    } catch (error) {
        console.error('Error getting owner pets: ', error);
        return [];
    }
};

// Creates likes
export const createLike = async (
    userId: string, 
    petId: string, 
    ownerId: string, 
    userPetId: string, 
    action: 'like' | 'pass'
): Promise<void> => {

    try {
        const likesRef = collection(db, COLLECTIONS.LIKES);

        // Building the like data object
        const likeData: Omit<Like, 'id'> = {
            userId, 
            petId,
            ownerId,
            userPetId,
            action,
            matched: false,
            createdAt: new Date(),
            matchedAt: undefined
        };

        // Save to firestore with auto-generated ID
        await addDoc(likesRef, {
            ...likeData,
            createdAt: Timestamp.fromDate(likeData.createdAt)
        });

        console.log('Like recorded for pet: ', petId);

    } catch (error) {
        console.error('Error creating like: ', error);
        throw error;
    }
};


// Prevent showing pet a user has already liked or passed on
export const hasUserInteractedWithPet = async (
    userId: string,
    petId: string
): Promise<boolean> => {

    try {
        const likesRef = collection(db, COLLECTIONS.LIKES);

        const q = query(
            likesRef, 
            where('userId', '==', userId),
            where('petId', '==', petId),
            limit(1) // no need to check if there's more than one
        );

        // Check if documents were found

        // Execute the query
        const snapshot = await getDocs(q);

        // If snapshot is empty, then there was no interaction
        return !snapshot.empty;
    } catch (error) {
        console.error('Error checking interaction: ', error);

        // if there's an error, show the pet
        return false;
    }
};


// Timestamp to date converter 
export const TimestampToDate = (timestamp: any): Date => {

    // Check if timestamp exists and has the toDate method
    if (timestamp && timestamp.toDate) {
        // then convert the timestamp to Date
        return timestamp.toDate();
    }

    return new Date();
}; 

// An example so I don't forget: 

// converting to firestore data 
// const data = doc.data();
// const createdDate = timestampToDate(data.createdAt);

// converting from firestore data
// const verifiedDate = timestampToDate(data.verifiedAt);



