import { db } from '@/config/firebase';
import { Pet } from '@/types/database';
import {
    arrayRemove,
    arrayUnion,
    collection,
    doc,
    GeoPoint,
    getDoc,
    getDocs,
    query,
    serverTimestamp,
    setDoc,
    Timestamp,
    updateDoc,
    where,
} from 'firebase/firestore';
import { COLLECTIONS } from './collections';
import { getUserById } from './userService';

// Create Pet when a user adds a new pet to their profile
export const createPet = async ( petData: {
    ownerId: string;
    name: string;
    breed: string;
    age: number;
    type?: string,
    size?: string,
    gender?:string,
    photo?:string,
    photos?: string[];
    personalityTraits?: string[];
    lookingFor?: string[];
    healthInfo?: {
        vaccinated?: boolean;
        spayedNeutered?: boolean;
        healthNotes?: string;
    };
    verification?: {
        microchipNumber?: string;
        verifiedAt?: null;
        verified?: boolean;
    };
}): Promise<string> => {
    try {
        // Get reference to pets collection
        const petsRef = collection(db, 'pets');

        // Create a new ref with the autogenerated ID
        const newPetRef = doc(petsRef);

        // Use date for immediate reads
        const now = new Date();

        // Get the owner's location to be stored with the pet
        let ownerGeopoint = null;
        try {
            const owner = await getUserById(petData.ownerId);
            if (owner?.geopoint) {
                ownerGeopoint = owner.geopoint;
            }
        } catch (error) {
            console.warn('could not get user location: ', error);
        }

        // Build the pet object
        const pet = {
            ...petData,
            id: newPetRef.id,
            photo: petData.photo || 'https://freepng.com/uploads/images/202311/vector-cute-doghappy-face-brown-color-png_1020x-3867.jpg',
            type: petData.type || 'Dog',
            size: petData.size || 'Medium',
            gender: petData.gender || 'Male',
            bio: `Meet ${petData.name}!`,
            personalityTraits: petData.personalityTraits || [],
            lookingFor: petData.lookingFor || [],
            healthInfo: petData.healthInfo || {
                vaccinated: false,
                spayedNeutered: false,
                healthNotes: '',
            },
            verification: petData.verification || {
                verified: false,
                microchipNumber: '',
                verifiedAt: null,
            },
            isActive: true,
            createdAt: now,
            updatedAt: now,
            ownerGeopoint: ownerGeopoint,
        };

        //Save the pet doc to Firestore
        await setDoc(newPetRef, pet);

        // console log
        console.log('Pet created')

        // add this pet to the user's petIds array
        const userRef = doc(db, 'users', petData.ownerId);
        await updateDoc(userRef, {
            // Only add to array if the value doesn't already exist (this prevents duplicates)
            petIds: arrayUnion(newPetRef.id),
        });

        console.log('Pet ID added to users array');

        return newPetRef.id;

    } catch (error) {
        console.error('Error creating the pet: ', error)
        throw error;
    }

};

// Updates pet info
export const updatePet = async (
    petId: string,
    data: {
        name?: string;
        breed?: string;
        age?: number;
        type?: string;
        size?: string;
        gender?: string;
        photo?: string;
        photos?: string[];
        bio?: string;
        personalityTraits?: string[];
        lookingFor?: string[];
        healthInfo?: {
            vaccinated?: boolean;
            spayedNeutered?: boolean;
            healthNotes?: string;
        };
        verification?: {
            microchipNumber?: string;
            verifiedAt?: Date | null;
            verified?: boolean;
        };
    }
): Promise<void> => {
    try {
        // Create ref to the pet document
        const petRef = doc(db, COLLECTIONS.PETS, petId);

        //Update only the fields that were provided
        await updateDoc(petRef, {
            ...data,
            updatedAt: new Date(),
        });

        console.log('Pet updated successfully: ', petId);
    } catch (error) {
        console.error('Error updating pet: ', error);
        throw error;
    }
};

//Delete a pet
export const deletePet = async (petId: string): Promise<void> => {
    try {
        // First, get the pet to find the owner
        const petRef = doc(db, COLLECTIONS.PETS, petId);
        const petSnap = await getDoc(petRef);

        if (!petSnap.exists()) {
            throw new Error('Pet not found');
        }

        const petData = petSnap.data();
        const ownerId = petData.ownerId;

        //  Mark as inactive
        await updateDoc(petRef, {
            isActive: false,
            updatedAt: new Date(),
        });

        // Remove the pet ID from the user's array of petIds
        const userRef = doc(db, COLLECTIONS.USERS, ownerId);
        await updateDoc(userRef, {
            petIds: arrayRemove(petId),
            updatedAt: serverTimestamp(),
        })

        console.log('Pet deleted successfully: ', petId);
    } catch (error) {
        console.error('Error deleting pet: ', error);
        throw error;
    }
}

// Get the active pets (for the explore screen)
export const getActivePets = async (): Promise<Pet[]> => {
    try {
        const petsRef = collection(db, COLLECTIONS.PETS);

        // Build the query
        const q = query(
            petsRef,
            where('isActive', '==', true),

            //orderBy('createdAt', 'desc')
        );

        // Executes the query
        const snapshot = await getDocs(q);

        // Turns the docs from firestore to pet objects
        return snapshot.docs.map(doc => {
            const data = doc.data();

        //Helper for timestamps
            const toDate = (timestamp: any): Date => {
                if (!timestamp) return new Date();
                if (timestamp instanceof Date) return timestamp;
                if (typeof timestamp.toDate === 'function') return timestamp.toDate();
                return new Date();
            };

            return {
                id: doc.id,
                ...data,
                createdAt: toDate(data.createdAt),
                updatedAt: toDate(data.updatedAt),
                verification: {
                    verified: data.verification?.verified || false,
                    microchipNumber: data.verification?.microchipNumber || '',
                    verifiedAt: data.verification?.verifiedAt?.toDate() || null
                }
            } as Pet;
        });
    } catch (error) {
        console.error('Error getting pets: ', error)
        return[];
    }
};

// Get Pets by owner ID
export const getPetsByOwnerId = async (ownerId: string): Promise<Pet[]> => {
    try {
        const petsRef = collection(db, 'pets');
        // Get the collection reference
        const q = query(
            petsRef,
            where('ownerId', '==', ownerId),
            where('isActive', '==', true)
        );

        // Execute query
        const snapshot = await getDocs(q);

        const pets = snapshot.docs.map((doc) => {
            const data = doc.data();


            // Helper function to safely convert timestamps to Date
            const toDate = (timestamp: any): Date => {
                if (!timestamp) return new Date();
                if (timestamp instanceof Date) return timestamp;
                if (typeof timestamp.toDate === 'function') return timestamp.toDate();
                return new Date();
            };

            // Build pet object with all fields having defaults
            const pet: Pet = {
                id: data.id || doc.id,
                ownerId: data.ownerId || ownerId,
                name: data.name || 'Unknown',
                breed: data.breed || 'Unknown',
                age: data.age || 0,
                type: data.type || 'Dog',
                size: data.size || 'Medium',
                gender: data.gender || 'Male',
                photo: data.photo || 'https://placedog.net/400',
                photos: Array.isArray(data.photos) ? data.photos : [],
                bio: data.bio || `Meet ${data.name || 'this pet'}!`,
                personalityTraits: Array.isArray(data.personalityTraits) ? data.personalityTraits : [],
                lookingFor: Array.isArray(data.lookingFor) ? data.lookingFor : [],

                healthInfo: {
                vaccinated: data.healthInfo?.vaccinated || false,
                spayedNeutered: data.healthInfo?.spayedNeutered || false,
                healthNotes: data.healthInfo?.healthNotes || '',
                },

                verification: {
                verified: data.verification?.verified || false,
                microchipNumber: data.verification?.microchipNumber || '',
                verifiedAt: data.verification?.verifiedAt ? toDate(data.verification.verifiedAt) : null,
                },

                isActive: data.isActive !== undefined ? data.isActive : true,
                createdAt: toDate(data.createdAt),
                updatedAt: toDate(data.updatedAt),
            };

            // Add optional ownerGeopoint if it exists
            if (data.ownerGeopoint) {
                pet.ownerGeopoint = data.ownerGeopoint;
            }

            return pet;
            });

            console.log('Returning', pets.length, 'pets');
            return pets;

        } catch (error) {
            console.error('Error in getPetsByOwnerId:', error);
            throw error;
        }
        };

// When a user changes their location, update ownerGeopoint on all their active pets
// so that distance filtering on the explore screen stays accurate
export const updatePetsOwnerGeopoint = async (
    userId: string,
    latitude: number,
    longitude: number
): Promise<void> => {
    try {
        const petsRef = collection(db, COLLECTIONS.PETS);
        const q = query(
            petsRef,
            where('ownerId', '==', userId),
            where('isActive', '==', true)
        );
        const snapshot = await getDocs(q);

        if (snapshot.empty) return;

        // Update all pets at the same time
        await Promise.all(
            snapshot.docs.map(petDoc =>
                updateDoc(petDoc.ref, {
                    ownerGeopoint: new GeoPoint(latitude, longitude),
                })
            )
        );

        console.log('Updated ownerGeopoint for', snapshot.docs.length, 'pets');
    } catch (error) {
        console.error('Error updating pets geopoint:', error);
        throw error;
    }
};

// Get pets with pending microchip verification (admin only)
export const getPendingVerificationPets = async (): Promise<Pet[]> => {
    try {
        const petsRef = collection(db, COLLECTIONS.PETS);
        const q = query(
            petsRef,
            where('isActive', '==', true),
            where('verification.verified', '==', false),
        );
        const snapshot = await getDocs(q);

        const toDate = (ts: any): Date => {
            if (!ts) return new Date();
            if (ts instanceof Date) return ts;
            if (typeof ts.toDate === 'function') return ts.toDate();
            return new Date();
        };

        // Only return pets that actually have a microchip number submitted
        return snapshot.docs
            .map(doc => {
                const data = doc.data();
                return {
                    id: doc.id,
                    ...data,
                    createdAt: toDate(data.createdAt),
                    updatedAt: toDate(data.updatedAt),
                    verification: {
                        verified: data.verification?.verified || false,
                        microchipNumber: data.verification?.microchipNumber || '',
                        verifiedAt: data.verification?.verifiedAt ? toDate(data.verification.verifiedAt) : null,
                    },
                } as Pet;
            })
            .filter(pet => pet.verification.microchipNumber && pet.verification.microchipNumber.trim() !== '');
    } catch (error) {
        console.error('Error getting pending verifications:', error);
        return [];
    }
};

// Approve or reject a microchip verification (admin only)
export const updatePetVerification = async (
    petId: string,
    approved: boolean,
    adminId: string
): Promise<void> => {
    try {
        const petRef = doc(db, COLLECTIONS.PETS, petId);
        await updateDoc(petRef, {
            'verification.verified': approved,
            'verification.verifiedAt': approved ? Timestamp.now() : null,
            'verification.verifiedBy': approved ? adminId : null,
            updatedAt: serverTimestamp(),
        });
        console.log(`Pet ${petId} verification ${approved ? 'approved' : 'rejected'}`);
    } catch (error) {
        console.error('Error updating verification:', error);
        throw error;
    }
};
